// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var fraction, initialOffset, scrollDistance, toTop, win;
    win = $(window);
    scrollDistance = win.width();
    initialOffset = parseInt($(".title-bar").css('top'));
    toTop = initialOffset - 150;
    fraction = toTop / (scrollDistance * .5);
    win.resize(function() {
      scrollDistance = win.width();
      initialOffset = parseInt($(".title-bar").css('top'));
      toTop = initialOffset - 150;
      return fraction = toTop / scrollDistance;
    });
    return $(window).scroll(function(e) {
      var $contact, $projects, left;
      left = win.scrollLeft();
      $projects = $($(".page")[1]);
      $contact = $($(".page")[2]);
      if (left < scrollDistance * .5) {
        return $(".title-bar").css('top', "" + (initialOffset - left * fraction) + "px");
      } else if (left < scrollDistance) {
        $projects.css('left', "" + (scrollDistance - left) + "px");
        return $(".title-bar").css('top', (initialOffset - toTop) + 'px');
      } else if (left < scrollDistance * 2) {
        $contact.css('left', "" + (scrollDistance * 2 - left) + "px");
        return $projects.css('left', "0px");
      } else {
        return $contact.css('left', "0px");
      }
    });
  });

}).call(this);
