// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var $nav0, $nav1, $nav2, $nav3, $page1, $page2, $page3, fraction, initialOffset, pageWidth, toTop, win;
    win = $(window);
    pageWidth = win.width();
    initialOffset = parseInt($(".title-bar").css('top'));
    toTop = initialOffset - 150;
    fraction = toTop / (pageWidth * .5);
    $page1 = $($(".page")[1]);
    $page2 = $($(".page")[2]);
    $page3 = $($(".page")[3]);
    $nav0 = $($("a.nav")[0]);
    $nav1 = $($("a.nav")[1]);
    $nav2 = $($("a.nav")[2]);
    $nav3 = $($("a.nav")[3]);
    $("body").resize(function() {
      pageWidth = win.width();
      initialOffset = parseInt($(".title-bar").css('top'));
      toTop = initialOffset - 150;
      return fraction = toTop / pageWidth;
    });
    $(window).scroll(function(e) {
      var activeNav, left;
      $(".title-bar ul a").removeClass("active");
      left = win.scrollLeft();
      $(".title-bar").css('top', left < pageWidth * .5 ? "" + (initialOffset - left * fraction) + "px" : '150px');
      $(".above-title-bar").css('height', left < pageWidth * .5 ? "" + (initialOffset - left * fraction) + "px" : '150px');
      $page1.css('left', left < pageWidth ? "" + (pageWidth - left) + "px" : '0px');
      $page2.css('left', left < pageWidth * 2 ? "" + (pageWidth * 2 - left) + "px" : '0px');
      $page3.css('left', left < pageWidth * 3 ? "" + (pageWidth * 3 - left) + "px" : '0px');
      activeNav = $($("a.nav")[Math.round(left / pageWidth)]);
      return activeNav.addClass("active");
    });
    $nav0.click(function(e) {
      return $("html, body").animate({
        scrollLeft: 0
      }, 750);
    });
    $nav1.click(function(e) {
      return $("html, body").animate({
        scrollLeft: pageWidth
      }, 750);
    });
    $nav2.click(function(e) {
      return $("html, body").animate({
        scrollLeft: pageWidth * 2
      }, 750);
    });
    return $nav3.click(function(e) {
      return $("html, body").animate({
        scrollLeft: pageWidth * 3
      }, 750);
    });
  });

}).call(this);
